# -*- coding: utf-8 -*-
"""sql.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxl9UKo5zflegfumHbqCCzG7RRNuDuFA
"""

-- Create the People Table
CREATE TABLE IF NOT EXISTS people (
    Id INT PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    Age INT NOT NULL,
    Job TEXT NOT NULL
);

-- Insert Data into People Table
INSERT INTO people (Id, Name, Age, Job) VALUES
(1, 'Alan', 11, 'Unemployed'),
(2, 'Bob', 22, 'Gamer'),
(3, 'Chuck', 33, 'Farmer'),
(4, 'Dave', 44, 'Painter'),
(5, 'Ed', 55, 'Writer'),
(6, 'Fred', 66, 'Writer'),
(7, 'Greg', 77, 'Writer'),
(8, 'Hank', 88, 'Retired'),
(9, 'Ike', 99, 'Retired');

-- Create the Income Table
CREATE TABLE IF NOT EXISTS income (
    Job TEXT PRIMARY KEY NOT NULL,
    Income INT NOT NULL
);

-- Insert Data into Income Table
INSERT INTO income (Job, Income) VALUES
('None', 0),
('Farmer', 200000),
('Painter', 100000),
('Writer', 50000),
('Retired', 0),
('Baker', 80000);

-- Subquery: Select Names from People where their Job earns more than 50000
SELECT Name
FROM people
WHERE Job IN (
    SELECT Job
    FROM income
    WHERE Income > 50000
);
    Name TEXT NOT NULL,
-- Create the People Table
CREATE TABLE IF NOT EXISTS people (
    Id INT PRIMARY KEY NOT NULL,
    Name TEXT NOT NULL,
    Age INT NOT NULL,
    Job TEXT NOT NULL
);

-- Insert Data into People Table
INSERT INTO people (Id, Name, Age, Job) VALUES
(1, 'Alan', 11, 'Unemployed'),
(2, 'Bob', 22, 'Gamer'),
(3, 'Chuck', 33, 'Farmer'),
(4, 'Dave', 44, 'Painter'),
(5, 'Ed', 55, 'Writer'),
(6, 'Fred', 66, 'Writer'),
(7, 'Greg', 77, 'Writer'),
(8, 'Hank', 88, 'Retired'),
(9, 'Ike', 99, 'Retired');

-- Create the Income Table
CREATE TABLE IF NOT EXISTS income (
    Job TEXT PRIMARY KEY NOT NULL,
    Income INT NOT NULL
);

-- Insert Data into Income Table
INSERT INTO income (Job, Income) VALUES
('None', 0),
('Farmer', 200000),
('Painter', 100000),
('Writer', 50000),
('Retired', 0),
('Baker', 80000);

-- Subquery: Select Names from People where their Job earns more than 50000
SELECT Name
FROM people
WHERE Job IN (
    SELECT Job
    FROM income
    WHERE Income > 50000
);
INSERT INTO people (Id, Name, Age, Job) VALUES
(1, 'Alan', 11, 'Unemployed'),
(2, 'Bob', 22, 'Gamer'),
(3, 'Chuck', 33, 'Farmer'),
(4, 'Dave', 44, 'Painter'),
(5, 'Ed', 55, 'Writer'),
(6, 'Fred', 66, 'Writer'),
(7, 'Greg', 77, 'Writer'),
(8, 'Hank', 88, 'Retired'),
(9, 'Ike', 99, 'Retired');

-- Create the Income Table
CREATE TABLE IF NOT EXISTS income (
    Job TEXT PRIMARY KEY NOT NULL,
    Income INT NOT NULL
);

-- Insert Data into Income Table
INSERT INTO income (Job, Income) VALUES
('None', 0),
('Farmer', 200000),
('Painter', 100000),
('Writer', 50000),
('Retired', 0),
('Baker', 80000);

-- Subquery: Select Names from People where their Job earns more than 50000
SELECT Name
FROM people
WHERE Job IN (
    SELECT Job
    FROM income
    WHERE Income > 50000
);